### ISSUE TITLE
Fatal warning using ocaml >= 4.03.0

### ISSUE THREAD

**Issue by constfun** [astrada/ocamlfuse#6]
According to [this](http://stackoverflow.com/a/37426097), as of 4.03.0, Warning 31 is fatal.
I'm not sure this is strictly an `ocamlfuse` issue, so apologies in advance if it isn't.

```
devbox% cat fuse_test.ml
let () = ()

devbox% ocamlfind ocamlc -linkpkg -thread -package fuse fuse_test.ml

File "/Users/nick/.opam/4.04.0/lib/fuse/Fuse.cma(Bigarray)", line 1:
Warning 31: files /Users/nick/.opam/4.04.0/lib/fuse/Fuse.cma(Bigarray) and /Users/nick/.opam/4.04.0/lib/ocaml/bigarray.cma(Bigarray) both define a module named Bigarray

File "fuse_test.ml", line 1:
Error: Some fatal warnings were triggered (1 occurrences)
``` 

I'm not sure how to deal with this error. Isn't the ocamlfuse Bigarray namespaced to Fuse–at the very least until I `open Fuse`?

Now if I throw Lwt into the mix, I get even more errors of a similar flavor.

```
devbox% cat fuse_test.ml
open Lwt

let () = ()

devbox% ocamlfind ocamlc -linkpkg -thread -package fuse -package lwt.unix fuse_test.ml                                                                             

File "/Users/nick/.opam/4.04.0/lib/fuse/Fuse.cma(Bigarray)", line 1:
Warning 31: files /Users/nick/.opam/4.04.0/lib/fuse/Fuse.cma(Bigarray) and /Users/nick/.opam/4.04.0/lib/ocaml/bigarray.cma(Bigarray) both define a module named Bigarray

File "fuse_test.ml", line 1:
Error: Files fuse_test.cmo
       and /Users/nick/.opam/4.04.0/lib/fuse/Fuse.cma(Result)
       make inconsistent assumptions over interface Result
```

**Comment by astrada** [comment]
Yes, I can reproduce the errors even on Ubuntu. Curiously enough, `ocamlopt` does not complain (that's why I didn't notice it):

    alex:~/tmp$ ocamlfind ocamlopt -linkpkg -thread -package Fuse fuse_test.ml -o fuse_test.native
    File "_none_", line 1:
    Warning 58: no cmx file was found in path for module Fuse, and its interface was not compiled with -opaque

While I don't have the same problem about the Result module linking with lwt:

    alex:~/tmp$ ocamlfind ocamlc -linkpkg -thread -package Fuse -package lwt.unix fuse_test.ml -o fuse_test.byte
    File "/home/alex/.opam/4.04.0/lib/Fuse/Fuse.cma(Bigarray)", line 1:
    Warning 31: files /home/alex/.opam/4.04.0/lib/Fuse/Fuse.cma(Bigarray) and /home/alex/.opam/4.04.0/lib/ocaml/bigarray.cma(Bigarray) both define a module named Bigarray
    File "fuse_test.ml", line 1:
    Error: Some fatal warnings were triggered (1 occurrences)

Disabling the warning, as explained in the Stackoverflow post, works:

    alex:~/tmp$ ocamlfind ocamlc -linkpkg -thread -package Fuse -warn-error -a fuse_test.ml -o fuse_test.byte
    File "/home/alex/.opam/4.04.0/lib/Fuse/Fuse.cma(Bigarray)", line 1:
    Warning 31: files /home/alex/.opam/4.04.0/lib/Fuse/Fuse.cma(Bigarray) and /home/alex/.opam/4.04.0/lib/ocaml/bigarray.cma(Bigarray) both define a module named Bigarray

In the case of Bigarray, I don't think it can create problems, because the "duplicated" module is exactly the same. Result module is another issue: it really should not be exported, because it's used internally and it's not referenced in `.mli` files. When I started maintaining this package, I tried to make it work making minimum changes, so I left the Makefile as it was. If you have the time to review the Makefile (or to upgrade it to a more modern build system), I will be happy to get your pull requests.
